environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: i686-pc-windows-msvc
  - TARGET: i686-pc-windows-gnu
  GH_TOKEN:
    secure: e2/vp8nNMaW1jJzM5gd6SK/wl45BjumwEFtfEaWiQCxagAE0zz8feZkDBVbt1DLk

install:
  - SET PATH=C:\Python34;C:\Python34\Scripts;%PATH%
  - SET PATH=%PATH%;%APPDATA%\Python\Scripts
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test
  - cargo doc --no-deps

after_test:
  - git clone https://github.com/alexcrichton/travis-cargo
  - set PYTHONPATH=%CD%/travis-cargo;%PYTHONPATH%
  - python -c "import travis_cargo; travis_cargo.main()" doc-upload
